### PR TITLE
build 1.19.5

### LINKED ISSUE #27: @conda-forge-admin, please update version
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The bot seems to be having trouble with the version update here: #28
fixes #27 
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
Windows build failing with
```
FAILED: tests/CMakeFiles/testframework.dir/catch_amalgamated.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DHAVE_VISIBILITY -DIS_BIG_ENDIAN=0 -DLIBHEIF_EXPORTS -I%SRC_DIR%\build -I%SRC_DIR%\libheif -I%SRC_DIR%\libheif\api -I%SRC_DIR%\include\libheif -I%SRC_DIR%\include /DWIN32 /D_WINDOWS /GR /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD -WX /showIncludes /Fotests\CMakeFiles\testframework.dir\catch_amalgamated.cpp.obj /Fdtests\CMakeFiles\testframework.dir\testframework.pdb /FS -c %SRC_DIR%\tests\catch_amalgamated.cpp
%SRC_DIR%\tests\catch_amalgamated.cpp(8072): error C2593: 'operator <<' is ambiguous
%SRC_DIR%\tests\catch_amalgamated.cpp(6598): note: could be 'std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)'
%SRC_DIR%\tests\catch_amalgamated.hpp(773): note: or       'std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)' [found using argument-dependent lookup]

```

**Comment by frmdstryr** [comment]
Can you try setting `BUILD_TESTING` off on windows? https://github.com/strukturag/libheif/blob/33ec3d63470944906dbccffa085970083969de3a/CMakeLists.txt#L553

Edit: In https://github.com/conda-forge/libheif-feedstock/blob/main/recipe/bld.bat

**Comment by frmdstryr** [comment]
Also I think the bot is complaining about `{℅-` at https://github.com/conda-forge/libheif-feedstock/blob/f4ba8f5259d8e8c68e17b68761f072d73b149185/recipe/meta.yaml#L7, can you try removing the dash or that whole if. Edit nevermind thats not a typo. Ping @hmaarrfk

**Comment by akrherz** [comment]
Thanks @frmdstryr for the review.

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
